### ISSUE TITLE
add MSSQL testing via Travis CI and docker images

### ISSUE THREAD

**Issue by photodude** [joomla-framework/database#67]
### Steps to reproduce the issue
no continuous integration testing is currently performed on some database platforms like MSSQL, etc

### Expected result
Test against all our database platforms like MSSQL, etc

### Actual result
no continuous integration testing is currently performed 

### Additional comments
I recently read the following

>The SQL Server for Linux preview is available as a docker image. Assuming we can setup Travis to protect our access key to the private preview, we could use docker on Travis CI builds to execute against tests SQL Server.
>
> https://www.microsoft.com/en-us/server-cloud/sql-server-on-linux.aspx
>
> https://docs.travis-ci.com/user/docker/

(I am aware that the CMS 4.x is dropping MSSQL and that the Framework may follow at some point due to low usage and lack of CI testing)

**Comment by mbabker** [comment]
It's only fairly recently that Microsoft created a Linux compatible version of their SQL Server resources which is why it's never been supported before.  Apparently there are a few options on the market now, including looking into AppVeyor.

**Comment by photodude** [comment]
Apparently, someone has a workaround for testing Oracle DB on travis ci as well https://github.com/cbandy/travis-oracle

an Oracle account is required and the Oracle username and password has to be in the build environment variables either as hidden repository settings or encrypted variables

**Comment by photodude** [comment]
@mbabker AppVeyor might be a great option considering it's Free for open-source projects.

What would it take to get an account so we can implement AppVeyor CI here and in the CMS?

**Comment by mbabker** [comment]
I've set up an account linked with the @joomla-bot GitHub account.

https://ci.appveyor.com/project/joomla/database

So, now we just need to get everything configured.

**Comment by photodude** [comment]
I've looked a little bit at it. we need to figure out what's needed for the appveyor.yml https://blog.wyrihaximus.net/2016/11/running-php-unit-tests-on-windows-using-appveyor-and-chocolatey/
maybe something like this will work

```yml
build: false
shallow_clone: false
platform:
  - x64
clone_folder: C:\projects\database
branches:
  except:
    - gh-pages
## Build matrix for lowest and highest possible targets
environment:
  matrix: # matrix will build PHP 5.6 and PHP 7.0
  - dependencies: lowest 
    php_ver_target: 7.0
  - dependencies: current
    php_ver_target: 7.0
  - dependencies: highest
    php_ver_target: 7.0
init:
  - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1
  - SET ANSICON=121x90 (121x90)
services:
  - mssql2014
  - mysql
  - postgresql
  - iis

## Install PHP and composer, and run the appropriate composer command
install:
    - IF EXIST c:\tools\php (SET PHP=0)
    - ps: appveyor-retry cinst --ignore-checksums -y php --version ((choco search php --exact --all-versions -r | select-string -pattern $Env:php_ver_target | Select-Object -first 1) -replace '[php|]','')
    - cd c:\tools\php
    - IF %PHP%==1 copy php.ini-production php.ini /Y
    - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
    - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar
    - cd c:\projects\php-project-workspace
    - IF %dependencies%==lowest appveyor-retry composer update --prefer-lowest --no-progress --profile -n
    - IF %dependencies%==current appveyor-retry composer install --no-progress --profile
    - IF %dependencies%==highest appveyor-retry composer update --no-progress --profile -n
    - composer show

test_script:
  - cd C:\projects\database
  - vendor/bin/phpunit -c phpunit.xml.dist
```
